"""groups_to_tests

Revision ID: 6c916c8a736a
Revises: b5ddefa007a7
Create Date: 2020-05-02 17:44:33.553338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c916c8a736a'
down_revision = 'b5ddefa007a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_to_tests',
    sa.Column('groups', sa.Integer(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groups'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['test'], ['tests.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_to_tests')
    # ### end Alembic commands ###
