"""groups_to_tests

Revision ID: 997b79c20a87
Revises: 6c916c8a736a
Create Date: 2020-05-02 17:45:35.639248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997b79c20a87'
down_revision = '6c916c8a736a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
